export const ACTION_TYPE = {
  ADD_COMMENT: 'ADD_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  SET_POST_DATA: 'SET_POST_DATA',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_MODAL: 'OPEN_MODAL',
  RESET_POST_DATA: 'RESET_POST_DATA',
};
